### ISSUE TITLE
Feature Request for Calibration Values Inclusion

### ISSUE THREAD

**Issue by ActionNerd** [praneshkmr/node-lsm303#1]
Hi!

Love the library.  I have used this pretty extensively over the past few days.  I would like to propose a few feature requests.  I've done the coding for them, however, I've never done pull requests, so you will have to bear with me.

I still have a tiny bit of work to do, but it will mostly be in util.js:

```
Utils.x_offset = 0;
Utils.y_offset = 0;
Utils.z_offset = 0;
```

And then a config function to change these from a main program:

```
Utils.setOffset = function(x, y, z) {
  this.x_offset = x;
  this.y_offset = y;
  this.z_offset = z;
  return;
}
```

And finally, an addition to buffToXYZMag that would look like this for x, y, and z:

```
    x: (this.twoscomp((buffer[0] << 8) | buffer[1],16) - this.x_offset),
```

I would love to contribute here, and if you give me a day or two, I will have the pull request ready.

**Comment by praneshkmr** [comment]
Hi ActionNerd,
           Thank you very much for using my library. Please take some time for writing some test code for the code you have developed and please make a pull request. 

Please note that I am currently not being active in development for this library, but would love contribution in any form, being new features, test codes,etc, as it would benefit other who may use this library in future. Thank You.

Regards
Pranesh Kumar.R

**Comment by ActionNerd** [comment]
Awesome, Pranesh!

I have the code just about ready.  I will submit them sometime this week in two separate commits: one for the calibration feature and one for the [heading feature](https://github.com/praneshkmr/node-lsm303/issues/2).

**Comment by ActionNerd** [comment]
Sorry, this is taking longer than I expected.  Should be done today or tomorrow.

**Comment by praneshkmr** [comment]
Hi ActionNerd,

```
                Please take some time to make quality code. No Hurries.
```

Regards,
Pranesh Kumar.R

On Wed, Jan 7, 2015 at 2:35 PM, ActionNerd notifications@github.com wrote:

> Sorry, this is taking longer than I expected. Should be done today or
> tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/praneshkmr/node-lsm303/issues/1#issuecomment-68995066
> .

## 

Regards
Pranesh Kumar R
